### ISSUE TITLE
wobbling window

### ISSUE THREAD

**Issue by kalkiboru111** [DoubleDice-com/beta#24] opened 2022-04-06 15:39 UTC
The site was vibrating when I tried to access it, specifically at the right hand margin of the window. This was right around the time of deployment to main net, so that may have been the issue, but for a moment I thought someone had slipped me some psychedelics.

**Comment by mz7mz7mz7** [comment] 2022-04-21 08:07
Duplicate of https://github.com/DoubleDice-com/beta/issues/23 , will close one of these tasks.

**Closed by mz7mz7mz7** 2022-04-21 08:07 UTC
Labels: bug, beta
